### ISSUE TITLE
UI Login for Contributors

### ISSUE THREAD

**Issue by JasonFritsche** [intelowlproject/IntelOwl-ng#157]
After installing dependencies and running npm start, I've started the app, and am at http://localhost:4200/auth/login. It looks like I need account credentials (username && password). Please advise on next steps for open source contributors.

**Comment by sp35** [comment]
HI @JasonFritsche, this is only the web client for https://github.com/intelowlproject/IntelOwl. So, To generate account credentials and see the client in action, you would need to setup the above project as well.

**Comment by m0mosenpai** [comment]
Hey, @JasonFritsche ! You'll need to create a superuser in the Django backend and use the credentials to login into the app. LIke @sp35 said, you'll need to setup and run the backend for that since this is just purely the frontend repo. The steps for everything mentioned can be found in the docs: https://intelowl.readthedocs.io/en/latest/Installation.html

Feel free to join the Honeynet Slack incase you have other doubts while contributing to the project.

**Comment by JasonFritsche** [comment]
Thank you @sp35 and @m0mosenpai for the prompt response. I will install the backend based on the linked docs.
