### ISSUE TITLE
Add tags/mimetype search fields on the Dashboard

### ISSUE THREAD

**Issue by mlodic** [intelowlproject/IntelOwl-ng#26]

**Comment by Eshaan7** [comment]
After browsing through google alot, I have implemented the tags filtering, It will be pushed with my next PR.

There's no search field for mimetype because user can already filter file-mimetype or observable classification by clicking on the pie charts, that is why providing a search field is redundant. What do u think ?

**Comment by mlodic** [comment]
a) If the jobs are a few numbers it is easy to click on the tag, otherwise you should scroll until you find a specific tag. It depends on the use case. I think that your implementation is a good step forward. Later we can add the search field too, but with low priority I think

b) yes we can skip this

**Comment by Eshaan7** [comment]
Alright! Tags filtering was added in commit - https://github.com/intelowlproject/IntelOwl-ng/commit/145eeed02b025d09596c50fd0f3095b1b2a30492
